export const ErrorCodes = {
  OK: 'OK',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FORBIDDEN: 'FORBIDDEN',
  DATA_SCOPE_DENIED: 'DATA_SCOPE_DENIED',
  TARGET_NOT_FOUND: 'TARGET_NOT_FOUND',
  DEVICE_OFFLINE: 'DEVICE_OFFLINE',
  RELATION_NOT_CONFIGURED: 'RELATION_NOT_CONFIGURED',
  RELATION_FORBIDDEN: 'RELATION_FORBIDDEN',
  POLICY_NOT_EFFECTIVE: 'POLICY_NOT_EFFECTIVE',
  CONCURRENCY_LIMIT_REACHED: 'CONCURRENCY_LIMIT_REACHED',
  DECISION_NOT_FOUND: 'DECISION_NOT_FOUND',
  DECISION_NOT_ALLOWED: 'DECISION_NOT_ALLOWED',
  DECISION_ALREADY_CONSUMED: 'DECISION_ALREADY_CONSUMED',
  DECISION_EXPIRED: 'DECISION_EXPIRED',
  SESSION_NOT_VISIBLE: 'SESSION_NOT_VISIBLE',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_ALREADY_ENDED: 'SESSION_ALREADY_ENDED',
  SESSION_NOT_STOPPABLE: 'SESSION_NOT_STOPPABLE',
  ORDER_ALREADY_EXISTS: 'ORDER_ALREADY_EXISTS',
  STARTUP_TIMEOUT: 'STARTUP_TIMEOUT',
  SAFETY_PROTECTION_TRIGGERED: 'SAFETY_PROTECTION_TRIGGERED',
  ORDER_REVIEW_REQUIRED: 'ORDER_REVIEW_REQUIRED',
  WORK_ORDER_STATE_INVALID: 'WORK_ORDER_STATE_INVALID',
  AI_HIGH_RISK_INTENT: 'AI_HIGH_RISK_INTENT',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
