type TransportPolicyInput = {
  retry_limit?: number;
  sent_timeout_seconds?: number;
  heartbeat_timeout_seconds?: number;
  retry_base_delay_seconds?: number;
  retry_max_delay_seconds?: number;
};

type DeviceContractInput = {
  protocol_name: string;
  transport_policy: TransportPolicyInput;
};

export const SCAN_CONTROLLER_TRIAL_BASELINE = {
  controller_code: 'scan_irrigation_controller_trial_v1',
  controller_name: '扫码灌溉控制器（试验版）',
  business_scene: 'scan_to_irrigate',
  protocol_name: 'hj-device-v2',
  protocol_version: '1.0.0',
  first_hardware: {
    sku: 'SCAN-IRR-CTRL-4G',
    rev: 'A01',
    release_code: 'HW-SCAN-IRR-CTRL-4G-A01',
    display_name: '扫码灌溉控制器硬件 A01',
    release_notes: '试验首板，4G 单泵单阀控制器，用于扫码灌溉联调。',
  },
  first_software: {
    family: 'SCAN-IRRIGATION-CONTROL',
    version_semver: '0.1.0',
    release_code: 'SW-SCAN-IRRIGATION-CONTROL-v0.1.0',
    display_name: '扫码灌溉控制软件 v0.1.0',
    release_notes: '首发联调版本，覆盖注册、心跳、状态快照、配置下发、本地保护和扫码启动最小流程。',
  },
} as const;

export function buildScanControllerTrialSpec(input: DeviceContractInput) {
  const registerRequiredTopLevelFields = ['v', 't', 'i', 'm', 's', 'p'];
  const registerRequiredPayloadFields = [
    'controller_code',
    'device_name',
    'iccid',
    'hardware_sku',
    'hardware_rev',
    'software_family',
    'software_version',
    'protocol_version',
    'config_version',
    'feature_modules',
    'capability_version',
    'capability_hash',
    'config_bitmap',
    'actions_bitmap',
    'queries_bitmap',
    'limits',
    'resource_inventory',
    'time_synced',
  ];

  return {
    controller_profile: {
      controller_code: SCAN_CONTROLLER_TRIAL_BASELINE.controller_code,
      controller_name: SCAN_CONTROLLER_TRIAL_BASELINE.controller_name,
      business_scene: SCAN_CONTROLLER_TRIAL_BASELINE.business_scene,
      protocol_name: input.protocol_name,
      protocol_version: SCAN_CONTROLLER_TRIAL_BASELINE.protocol_version,
    },
    baseline_versions: {
      hardware: {
        release_kind: 'hardware',
        hardware_sku: SCAN_CONTROLLER_TRIAL_BASELINE.first_hardware.sku,
        hardware_rev: SCAN_CONTROLLER_TRIAL_BASELINE.first_hardware.rev,
        release_code: SCAN_CONTROLLER_TRIAL_BASELINE.first_hardware.release_code,
        display_name: SCAN_CONTROLLER_TRIAL_BASELINE.first_hardware.display_name,
        release_notes: SCAN_CONTROLLER_TRIAL_BASELINE.first_hardware.release_notes,
      },
      software: {
        release_kind: 'software',
        family: SCAN_CONTROLLER_TRIAL_BASELINE.first_software.family,
        version_semver: SCAN_CONTROLLER_TRIAL_BASELINE.first_software.version_semver,
        release_code: SCAN_CONTROLLER_TRIAL_BASELINE.first_software.release_code,
        display_name: SCAN_CONTROLLER_TRIAL_BASELINE.first_software.display_name,
        release_notes: SCAN_CONTROLLER_TRIAL_BASELINE.first_software.release_notes,
      },
    },
    registration_flow: [
      {
        step_no: 1,
        step_code: 'tcp_connect',
        title: '建立 TCP 连接',
        detail: '设备完成联网后立即建立 TCP 连接，AT 调试文本不得进入业务报文。',
      },
      {
        step_no: 2,
        step_code: 'time_sync',
        title: '检查时间状态',
        detail: '优先使用模组网络时间。未同步时应上报 time_synced=false，且禁止发送 1970 时间。',
      },
      {
        step_no: 3,
        step_code: 'send_register',
        title: '发送 RG',
        detail: '首包必须是 RG，补齐身份、软硬件版本、完整能力集和资源清单；feature_modules 不是完整能力集的替代品。',
      },
      {
        step_no: 4,
        step_code: 'enter_heartbeat_loop',
        title: '进入 HB 循环',
        detail: 'RG 成功入站后转入 HB 周期上报，同时按运行态独立发送 SS。',
      },
      {
        step_no: 5,
        step_code: 'accept_sync_config',
        title: '接受 SC 下发',
        detail: '平台通过 SC 下发配置，设备本地持久化完成后必须返回 AK。',
      },
    ],
    registration_requirements: {
      required_top_level_fields: registerRequiredTopLevelFields,
      required_payload_fields: registerRequiredPayloadFields,
      optional_payload_fields: [
        'controller_role',
        'deployment_mode',
        'signal_csq',
        'battery_soc',
        'module_model',
        'chip_sn',
        'control_config',
        'channel_bindings',
        'runtime_rules',
      ],
      validation_rules: [
        'TCP wire format must use the compact short envelope v/t/i/m/s with optional c/r/ts.',
        'The first packet must be RG and must not use protocol/type/msg_id/seq/payload top-level fields.',
        'i must be the device IMEI and must match the platform device ledger.',
        'software_version must use semver without a leading v.',
        'hardware identity must be split into hardware_sku + hardware_rev.',
        'RG must carry the full capability-set contract: capability_version + capability_hash + config_bitmap + actions_bitmap + queries_bitmap + limits.',
        'When time_synced=true, ts must be a valid ISO8601 UTC timestamp. Do not send 1970-01-01T00:00:00Z.',
        'Business payload must not contain modem AT text or raw modem response fragments.',
      ],
      platform_acceptance: [
        '平台可以解析并落库 RG。',
        '平台不再看到 invalid_frame_length / malformed_json。',
        '平台不再看到 ts=1970-01-01T00:00:00Z。',
        '设备详情页可回显 software_version、hardware_sku、hardware_rev、config_version、capability_version、capability_hash。',
      ],
    },
    telemetry_contract: {
      heartbeat: {
        recommended_interval_seconds: 30,
        configurable_via_runtime_rules_field: 'heartbeat_interval_sec',
        required_payload_fields: [
          'online',
          'ready',
          'config_version',
          'capability_hash',
          'workflow_state',
          'run_state',
          'power_state',
          'signal_csq',
          'battery_soc',
          'alarm_codes',
          'time_synced',
        ],
      },
      state_snapshot: {
        idle_interval_seconds: 120,
        running_interval_seconds: 10,
        alarm_burst_interval_seconds: 5,
        configurable_via_runtime_rules_fields: ['snapshot_idle_interval_sec', 'snapshot_running_interval_sec'],
        required_payload_fields: [
          'voltage_v',
          'current_a',
          'power_kw',
          'energy_kwh',
          'pressure_mpa',
          'flow_m3h',
          'total_m3',
          'pump_state',
          'valve_state',
        ],
      },
    },
    config_contract: {
      command_code: 'SYNC_CONFIG',
      required_fields: [
        'config_version',
        'feature_modules',
        'control_config',
        'channel_bindings',
        'runtime_rules',
        'protection_config',
      ],
      runtime_rule_fields: [
        'heartbeat_interval_sec',
        'snapshot_idle_interval_sec',
        'snapshot_running_interval_sec',
        'runtime_tick_interval_sec',
        'control_timeout_sec',
      ],
      protection_fields: [
        'overload_protection',
        'phase_loss_protection',
        'under_voltage_protection',
        'over_voltage_protection',
        'dry_run_protection',
        'pressure_high_limit',
        'pressure_low_limit',
        'start_delay_ms',
        'stop_delay_ms',
      ],
      ack_requirements: [
        '设备本地持久化完成后必须回复 AK。',
        'ACK payload 中必须回显 config_version。',
        '平台下发的 runtime_rules 生效后，设备应按新的 heartbeat_interval_sec、snapshot_idle_interval_sec 与 snapshot_running_interval_sec 运行。',
      ],
    },
    transport_policy: {
      retry_limit: input.transport_policy.retry_limit ?? 2,
      sent_timeout_seconds: input.transport_policy.sent_timeout_seconds ?? 30,
      heartbeat_timeout_seconds: input.transport_policy.heartbeat_timeout_seconds ?? 120,
      retry_base_delay_seconds: input.transport_policy.retry_base_delay_seconds ?? 15,
      retry_max_delay_seconds: input.transport_policy.retry_max_delay_seconds ?? 300,
    },
    sample_messages: {
      register: {
        v: 1,
        t: 'RG',
        i: '864502061234567',
        m: 'reg-0001',
        s: 1,
        ts: '2026-04-09T09:30:00Z',
        p: {
          controller_code: SCAN_CONTROLLER_TRIAL_BASELINE.controller_code,
          controller_role: 'scan_irrigation_controller',
          deployment_mode: 'standalone',
          device_name: SCAN_CONTROLLER_TRIAL_BASELINE.controller_name,
          iccid: '898604B4192401234567',
          hs: SCAN_CONTROLLER_TRIAL_BASELINE.first_hardware.sku,
          hr: SCAN_CONTROLLER_TRIAL_BASELINE.first_hardware.rev,
          ff: SCAN_CONTROLLER_TRIAL_BASELINE.first_software.family,
          fv: SCAN_CONTROLLER_TRIAL_BASELINE.first_software.version_semver,
          protocol_version: SCAN_CONTROLLER_TRIAL_BASELINE.protocol_version,
          cv: 1,
          fm: ['pdc', 'svl', 'cdr', 'pay'],
          cap_ver: 3,
          cap_hash: 'sha256:8d1a97f4c4d0f2b8',
          config_bitmap: '0x0000001f',
          actions_bitmap: '0x0000003f',
          queries_bitmap: '0x00000007',
          limits: {
            max_inflight_control: 1,
            event_queue_depth: 8,
            ota_block_bytes: 512,
          },
          ri: {
            relay_output: 2,
            digital_input: 4,
            analog_input: 3,
            net_session: 1,
          },
          time_synced: true,
        },
      },
      heartbeat: {
        v: 1,
        t: 'HB',
        i: '864502061234567',
        m: 'hb-0002',
        s: 2,
        ts: '2026-04-09T09:30:30Z',
        p: {
          on: true,
          rd: true,
          cv: 1,
          cap_hash: 'sha256:8d1a97f4c4d0f2b8',
          wf: 'RI',
          csq: 19,
          bs: 88,
          alarm_codes: [],
          time_synced: true,
        },
      },
      state_snapshot: {
        v: 1,
        t: 'SS',
        i: '864502061234567',
        m: 'snap-0003',
        s: 3,
        ts: '2026-04-09T09:31:00Z',
        p: {
          wf: 'RN',
          vv: 380.2,
          ia: 7.8,
          pw: 3.1,
          ek: 12.6,
          pr: 0.28,
          fm: 16.5,
          fq: 42.3,
          pump_state: 'running',
          valve_state: 'open',
        },
      },
    },
    embedded_codex_instruction: [
      '你现在要为“扫码灌溉控制器（试验版）”开发设备接入程序，按 48KB RAM 可落地的标准实现。',
      '后端与嵌入式 TCP 交互只允许短协议：v/t/i/m/s/c/r/p + RG/HB/SS/ER/QR/QS/EX/SC/AK/NK。',
      '不要再实现或发送 protocol/type/msg_id/seq/payload 这套长 envelope。',
      '内部业务语义可以继续映射到长名称，但线协议必须使用短码，例如 qcs/qwf/qem/spu/tpu/ovl/cvl。',
      `首个硬件版本固定为 ${SCAN_CONTROLLER_TRIAL_BASELINE.first_hardware.release_code}。`,
      `首个软件版本固定为 ${SCAN_CONTROLLER_TRIAL_BASELINE.first_software.release_code}。`,
      'TCP 传输固定为 4 字节大端长度前缀 + UTF-8 JSON。',
      '首包必须发送 RG，并包含 controller_code、device_name、iccid、hardware_sku、hardware_rev、software_family、software_version、protocol_version、config_version、feature_modules、capability_version、capability_hash、config_bitmap、actions_bitmap、queries_bitmap、limits、resource_inventory、time_synced。',
      '配置项、控制项、查询项和限制项共同构成正式能力集；feature_modules 只表示模块声明，不能替代完整能力集。',
      'HB 只发轻量状态，并按租约续命规则治理；已有 SS/ER/QS 等上行时不要额外补发冗余心跳。',
      '必须支持 SC，并在本地持久化完成后返回 AK，带回 config_version。',
      '控制类 EX 不允许设备侧缓存、不允许保留待执行队列；当前命令完成、拒绝、失败或超时后必须立即清空本地控制上下文。',
      '设备重连或重启后不得自动回放历史控制命令；平台中的 device_command 只是审计与投递真相源，不代表设备侧排队。',
      'OTA 必须按 manifest 事务执行；平台只在 boot_confirmed 后判定升级成功。',
      '必须支持本地保护和最小状态机实现，不要做兼容长协议的双栈。',
      '时间未同步时允许 time_synced=false，但绝不能发送 1970-01-01T00:00:00Z。',
      '不要 mock，不要 fake send，不要把 AT 文本混入业务流。',
    ].join('\n'),
  };
}
